
site_name: ymgmcmc
repo_url: https://github.com/naoya-horai/documents.git
site_url: https://ymgmcmc.com/documents/

copyright: 'Copyright © 2023-2030 - ymgmcmc'

nav: 
  - top: 
    - introduction: index.md
    - about: about.md
  - metal: 
    - metalとは: metal/metalとは.md
  - Houdini:
    - houdiniとは: houdini/houdiniとは.md
  - pipeline:
    - materialXを変換する: pipeline/materialXを変換する。
theme:
  name: material
  palette:
    primary: white
    accent: cyan
  favicon: favicon.ico
  language: ja
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant 

markdown_extensions:
  - attr_list
  
  - pymdownx.magiclink: