
site_name: ymgmcmc
repo_url: https://github.com/naoya-horai/documents.git
site_url: https://docs.ymgmcmc.com

copyright: 'Copyright © 2023-2030 - ymgmcmc'


theme:
  name: material
  palette:
    primary: white
    accent: slate
  favicon: favicon.ico
  language: ja
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant 

markdown_extensions:
  - attr_list
  - pymdownx.magiclink:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format