
site_name: ymgmcmc
repo_url: https://github.com/naoya-horai/documents.git
site_url: https://ymgmcmc.com/documents/

copyright: 'Copyright © 2023-2030 - ymgmcmc'

nav: 
  introduction: index.md
    - about: about.md
  - metal: metal/metal入門.md

theme:
  name: material
  favicon: favicon.ico
  language: ja
  features:
    - navigation.tabs
    - navigation.top